### ISSUE TITLE
how is this being mirrored?

### ISSUE THREAD

**Issue by mattip** [mozillazg/pypy#5]
I am a PyPy dev, and am considering how we can use some of the nice CI providers available to github projects but not available to other code hosting sites like foss.heptapod.net

I am curious how you are mirroring this. Is there a machine running a cron job somewhere? Would it be reasonable to mirror via a github actions cron task?

**Comment by mozillazg** [comment]
@mattip Sorry for my late reply.

> I am curious how you are mirroring this

I'm mirroring this via a fork version of https://github.com/fingolfin/git-remote-hg

> Is there a machine running a cron job somewhere? 

Yes. I'm running the job via crontab on my vps.

> Would it be reasonable to mirror via a github actions cron task?

Yes, it's possible. And I should merge to use github action instead of crontab, I'll try it later.

**Comment by mattip** [comment]
I think the version at https://github.com/mnauw/git-remote-hg works better

**Comment by mozillazg** [comment]
@mattip Thanks for your share, I'll try it when I start to merge the job.

**Comment by mozillazg** [comment]
@mattip I just create a demo for mirror hg repo with github action ( via https://github.com/mozillazg/git-remote-hg ) and it works as expected:

https://github.com/mozillazg/test-hg-mirror-with-gh-action

This repo will mirror https://foss.heptapod.net/pypy/buildbot to https://github.com/mozillazg/pypy-buildbot

**Comment by mozillazg** [comment]
> I mirrored this via a fork version of fingolfin/git-remote-hg

Sorry for this message, I misremembered. In fact, I used a fork version of https://github.com/felipec/git-remote-hg, I just have pushed the modified codes from my vps to https://github.com/mozillazg/git-remote-hg

**Comment by mattip** [comment]
Wow, thanks! What will happen the next time it runs, will it recreate the repo all over again or will it only pick up the changes?

**Comment by mozillazg** [comment]
It'll recreate the repo all over again, but `git push` will only push the changes.

**Comment by mgorny** [comment]
@mozillazg, have you made any progress wrt updating the automation for this repo? We find it very helpful for PyPy packaging on Gentoo but the mirroring delays are a bit of a problem.

Right now I see that `default` branch has been synced but the release branches or tags haven't.

**Comment by mozillazg** [comment]
@mgorny Thank you for your feedback. I haven't made any changes to the automated synchronization process recently, so it seems there might be an issue somewhere that has prevented the latest tags from being synced. I will fix it as soon as possible.

**Comment by mozillazg** [comment]
> Right now I see that default branch has been synced but the release branches or tags haven't.

@mgorny The issue has been resolved.

**Comment by mgorny** [comment]
> > Right now I see that default branch has been synced but the release branches or tags haven't.
> 
> @mgorny The issue has been resolved.

Thanks. Unfortunately, `release-pypy2.7-v7.3.12rc1` still isn't there, and `release-pypy2.7-v7.x` branch seems outdated.

**Comment by mozillazg** [comment]
> Unfortunately, `release-pypy2.7-v7.3.12rc1` still isn't there, and `release-pypy2.7-v7.x` branch seems outdated.

@mgorny Thank you for the reminder. After checking, I found that the reason these two branches were not synchronized is that there is a case in the data of these two branches that the git-remote-hg script I used cannot handle. I plan to try switching to https://github.com/mnauw/git-remote-hg.

**Comment by mozillazg** [comment]
@mgorny 

> Unfortunately, release-pypy2.7-v7.3.12rc1 still isn't there, and release-pypy2.7-v7.x branch seems outdated.

The issue has been resolved. Please check again.

* https://github.com/mozillazg/pypy/tree/release-pypy2.7-v7.3.12rc1
* https://github.com/mozillazg/pypy/tree/release-pypy2.7-v7.x

**Comment by mattip** [comment]
Thanks! Did you use https://github.com/mnauw/git-remote-hg as-is or did you need to modify it?

**Comment by mozillazg** [comment]
> Thanks! Did you use https://github.com/mnauw/git-remote-hg as-is or did you need to modify it?

@mattip 

The https://github.com/mnauw/git-remote-hg cannot handle the repository of PyPy. I am currently using https://github.com/mozillazg/git-remote-hg, which is modified based on the latest version of https://github.com/felipec/git-remote-hg.

**Comment by mozillazg** [comment]
> Would it be reasonable to mirror via a github actions cron task?

@mattip 

I have completed the migration and implemented regular synchronization using GitHub Actions today:

https://github.com/mozillazg/job-mirror-hg-repos/blob/master/.github/workflows/main.yml#L54-L67

**Comment by mattip** [comment]
Cool!

**Comment by mattip** [comment]
Maybe you could mention that repo in the README here or in the About blurb in the upper-right corner? Also, how can I contribute? I see a "donate" link but it goes to https://mozillazg.com/wechat_donate.jpeg, which unfortunately I cannot read.

**Comment by mozillazg** [comment]
> Maybe you could mention that repo in the README here or in the About blurb in the upper-right corner?

👌  I have updated the content of the About blurb to mention that repo.

> how can I contribute? I see a "donate" link but it goes to https://mozillazg.com/wechat_donate.jpeg, which unfortunately I cannot read.

No need to be so polite. Compared to your contributions to the PyPy community, my work is just a drop in the bucket. That donation link is only for Chinese developers, as GitHub Sponsor does not support bank accounts from China.

**Comment by mgorny** [comment]
Thanks a lot! Your work is of great help to us in Gentoo, and to me specifically as it saves me from having to figure out how to use Mercurial ;-).
